server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://121.40.166.14:3306/microServer?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=GMT%2B8&allowPublicKeyRetrieval=true
    username: root
    password: aliyun7@mysql
    driver-class-name: com.mysql.cj.jdbc.Driver
  data:
    redis:
      host: 121.40.166.14
      port: 6379
      password: redis123
      jedis:
        pool:
          min-idle: 0
          max-active: 8
          max-idle: 8
          max-wait: -1ms
      connect-timeout: 30000ms
mybatis-plus:
  mapper-locations: classpath*:mapper/*.xml
  global-config:
    db-config:
      logic-delete-field: isDel # 全局逻辑删除的实体字段名(since 3.3.0,配置后可以忽略不配置步骤2)
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)`
